alias ovaas-build="docker-compose build openvino_mode_server python"
alias ovaas-lcl="ovaas-build && docker-compose up"
alias ovaas-lcl-restart="docker-compose restart python"
alias ovaas-lcl-bash="docker-compose exec python bash"
alias ovaas-init="mkdir results images"
